# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 7.0
  - 7.1

env:
  - DB=MYSQL CORE_RELEASE=4.0

matrix:
  include:
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=4
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=4
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=4
    - php: 7.0
      env: DB=MYSQL CORE_RELEASE=4.1
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=4.1
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=4.1
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=4.1
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update || true
  - composer clear-cache
  - composer validate --strict
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - ./vendor/bin/phpunit ./vendor/friendsofsilverstripe/backendmessages/tests
